### ISSUE TITLE
DB schema: managing user' roles

### ISSUE THREAD

**Issue by longnd** [mcneto/onlinecourse_project#2]
One of the requirements for the people subscribing to the online course is:
> They also have to indicate if they are students, instructors, or people outside the institute

But refer to the current [DB schema](https://dbdiagram.io/d/5fe561599a6c525a03bc41ad): 
![image](https://user-images.githubusercontent.com/1896814/113550570-75d45600-961d-11eb-82ec-f5712ee7766b.png)

The **users** table has 2 columns:
* **instructor**: boolean
* **role**: string

I assume they created for the same purpose of managing user's roles, but if that is the case, we don't need both fields, the `role` field is enough to manage all kinds of roles: instructor, student, or general people. Or do you have another purpose for these fields?

**Comment by mcneto** [comment]
When I did the authentication part with devise and I tried to implement role into the project by using pundit, I created instructor boolean variable in order to specify if the user’s an instructor or not, but I still didn’t understand how to integrate this pundit part at the time.

As the boolean can only contain 2 values I guessed it will not cover normal people role anyway so I decided to use more simple solution by create the new role variable which is string to collect role data when sign up and use normal if-clause to implement the authorization part to the website which is not as secure as using pundit but at least can be functional at the moment.

But in the end, I implemented the pundit into the project used the instructor variable so that caused the database to have both variable that function a similar purpose which is a redundant indeed.

**Comment by longnd** [comment]
> But in the end, I implemented the pundit into the project used the instructor variable
That means you can remove the `role` column in the `users` table? In that case, how can use manage the 3 roles: instructor, students & general people? Please clarify if you have had an approach for that (but haven't implemented it)

IMO, using the `role` column is enough. We can also take advantage of the [ActiveRecord Enum](https://api.rubyonrails.org/classes/ActiveRecord/Enum.html) to keep track of the role without hardcoding the role as string in database. [This article](https://naturaily.com/blog/ruby-on-rails-enum) gives more example. 
So back to this project, in the User model we can do like this:
```ruby
# app/models/user.rb

class User < ApplicationRecord
  ...
  enum role: { instructor: 0, student: 1, general: 3 }
  ...
end

```
and then we can check the role of a user like this:
```ruby
user.instructor?
```

**Comment by mcneto** [comment]
I agree with you that I should use enum to manage roles because it would support 3 roles as in the challenge has described or more for the future plan. I only used boolean in this case because it’s less complicated for me to only mange 2 roles at that time.

**Comment by mcneto** [comment]
I agree with you that I should have used enum to manage roles because it would support 3 roles as in the challenge has described or more for the future plan. I only used boolean in this case because it’s less complicated for me to only mange 2 roles at that time as all these Ruby on Rails are very much new things for me.
