### ISSUE TITLE
DB schema: redundant or incomplete `course` table

### ISSUE THREAD

**Issue by longnd** [mcneto/onlinecourse_project#3]
Refer to the current [DB schema](https://github.com/mcneto/onlinecourse_project/blob/63b07d256b924bcfc3ed6e84c4f135629124aee1/db/schema.rb): https://dbdiagram.io/d/5fe561599a6c525a03bc41ad

<img width="1097" alt="Screen Shot 2021-04-05 at 12 31 29" src="https://user-images.githubusercontent.com/1896814/113540686-dc03ad80-960a-11eb-84ce-6aa06b7a73b2.png">

There is a `courses` table so I assume you want to manage the list of courses in this DB design even though it isn't required by the code challenge. But:
1. What is the meaning of the `user_id` column in the `courses` table? Is that the user who created the course? If it is, it should be named in a more declarative way, e.g. `created_user_id`
2. What is the relationship of this table with the other tables? What is it used for?
  Besides the relationship with the `users` table which may define who created each course, this table can't be used for any other purposes, e.g. showing which groups or attendants of a specific course.

**Comment by mcneto** [comment]
**For the first question**, It was right as you said I intend to use a user_id to specify the user who created the courses. I agree that is should be more declarative name and I will make an improvement next time in the naming process. Thank you for your direction and advice. 

**For the second question**, Course table was created to store the user data who apply to its course and also the group data which should be in the course as I firstly design the system according to these following ideas:

- Course are the main part of the website, user can create and subscribe in to it as the matter of role are indicated.
- In each course will have groups which will also include the user who is a member of those group in it.

But due to my incomplete part in the project, the subscribe function is unavailable so I only show normal course and group page separate which is still not fully functioning but can only create, edit, view simple info and delete it so there’s no relationship between course and group table yet.

**Comment by longnd** [comment]
> Course table was created to store the user data who apply to its course

The current structure of the `courses` table just has an `user_id` column to store the instructor who created the course. How do you plan to use that table to store the users who enrolled inIn each course will have groups which will also include the user who is a member of those group in it. a course?

> In each course will have groups which will also include the user who is a member of those groups in it.

The current design can't indicate the direct relationship between a course & groups (there is no relationship between the `courses` and `groups` table). Are you saying we can rely on the users in the groups who enrolled in a course?

**Comment by mcneto** [comment]
For my actual plan, workflow should be like this following:

1. When user sign in/sign up, it will insert or retrieve data to/from the Users table.

- For instructor, if they try to create the course it will insert data to the Courses table.
- For student, if they want to enroll the course it will insert data to the Enrollments table that will tell us who’s in the course.

2. Instructor can create the groups inside of course which will insert data to the Groups table that will tell us which group is in this course.
3. Instructor can assign some students into the group which will insert data to the Memberships table.

Which refer to the new database design from #1

![image](https://user-images.githubusercontent.com/70894675/114070096-dd163280-98c9-11eb-873c-d11e78445aa0.png)
